services:
  apache:
    build: docker/httpd
    container_name: apache
    working_dir: /var/www
    ports:
      - "8000:80"
    volumes:
      - "./httpd.conf:/usr/local/apache2/conf/extra/docker.conf"
      - "./:/var/www"
  php:
    build: docker/php
    container_name: php
    working_dir: /var/www
    volumes:
      - "./php.ini:/usr/local/etc/php/conf.d/999-docker.ini"
      - "./:/var/www"
  maildev:
    image: maildev/maildev
    container_name: maildev
    command: "bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS"
    ports:
      - "8025:80"