version: "3.7"
services:
  apache:
    build: docker/httpd
    container_name: apache
    working_dir: /var/www
    ports:
      - "8000:80"
    volumes:
      - "./httpd.conf:/usr/local/apache2/conf/extra/docker.conf"
      - "./:/var/www"
  php-fpm:
    build: docker/php-fpm
    container_name: php-fpm
    working_dir: /var/www
    volumes:
      - "./php.ini:/usr/local/etc/php/php.ini"
      - "./:/var/www"
  maildev:
    image: maildev/maildev:latest
    container_name: maildev
    command: "bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS"
    ports:
      - "8025:80"
x-docker:
  services:
    php-fpm: "foo"